### ISSUE TITLE
Odometer not updating value

### ISSUE THREAD

**Issue by cbaxter713** [wallin/angular-odometer#7]
I am implementing my angular odometer with a dynamic value that is changed frequently within my app: 

    <div class="bucket-count" odometer="{{ bucket.ProductCount }}"></div>

When my app initializes, the initial value of bucket.ProductCount in the odometer is animating in as expected, but whenever bucket.ProductCount is updated in the app logic to a new value, the odometer value on the screen does not update.  Is there something else I need to be doing to have that value auto update anytime the variable behind the scenes changes?

**Comment by wallin** [comment]
Hi Colin, try without the brackets, to make the plugin watch for change on the variable itself, not the value. i.e.:

```html
<div class="bucket-count" odometer="bucket.ProductCount"></div>
```

This should help

**Comment by cbaxter713** [comment]
Thanks, that did the trick! Big oversight on my part

**Comment by wallin** [comment]
great! glad to help
